openapi: 3.0.3
info:
  title: Party Organizer
  description: This is the server's swagger file for the Party Organizer project
  version: 1.2.1
servers:
  - url: http://localhost:8080/api/v1/
paths:
  /partyAttendanceManager/accept/{party_id}:
    get:
      tags:
        - Party Attendance Manager
      summary: Accept party invite
      description: Accept party invite
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_invite_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/decline/{party_id}:
    get:
      tags:
        - Party Attendance Manager
      summary: Decline party invite
      description: Decline party invite
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_invite_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/invite/{party_id}/{invited_username}:
    get:
      tags:
        - Party Attendance Manager
      summary: Send party invite to user
      description: Send party invite to user
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_invite_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/getPendingInvites/:
    get:
      tags:
        - Party Attendance Manager
      summary: Get all pending party invite for user
      description: Get all pending party invite for user
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_invite_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/getPartyPendingInvites/{party_id}:
    get:
      tags:
        - Party Attendance Manager
      summary: Get all pending party invite for party
      description: Get all pending party invite for party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_invite_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/kick/{party_id}/{friend_id}:
    get:
      tags:
        - Party Attendance Manager
      summary: Remove a user from a party
      description: Remove a user from a party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_message"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/joinPublicParty/{party_id}:
    get:
      tags:
        - Party Attendance Manager
      summary: Join public party
      description: Join public party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /partyAttendanceManager/joinPrivateParty/{party_id}/{access_code}:
    get:
      tags:
        - Party Attendance Manager
      summary: Join private party
      description: Join private party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
components:
  schemas:
    invite_body:
      type: object
      properties:
        invitor:
          $ref: "#/components/schemas/user"
        invited:
          $ref: "#/components/schemas/user"
        party:
          $ref: "#/components/schemas/party"
        state:
          type: string
          format: string
          example: "PENDING"
    user:
      type: object
      properties:
        id:
          type: integer
          format: integer
          example: 23
        username:
          type: string
          format: string
          example: "Joseph"
        email:
          type: string
          format: string
          example: "totally@real.email"
    party:
      type: object
      properties:
        id:
          type: integer
          format: integer
          example: 2
        organizer:
          $ref: "#/components/schemas/user"
        place:
          type: string
          format: string
          example: "Budapest"
        name:
          type: string
          format: string
          example: "party name"
        google_maps_link:
          type: string
          format: string
          example: "https://maps.app.goo.gl/BRWibuuYXGPDiAWP9"
        facebook_link:
          type: string
          format: string
          example: "https://www.facebook.com/"
        whatsapp_link:
          type: string
          format: string
          example: "https://web.whatsapp.com/"
        is_private:
          type: boolean
          format: boolean
          example: true
        access_code_enabled:
          type: boolean
          format: boolean
          example: false
        access_code:
          type: string
          format: string
          example: "DD45H1A"
    response_success_invite_data:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          $ref: '#/components/schemas/invite_body'
    response_success_invite_data_array:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/invite_body'
    response_success_party_data:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          $ref: '#/components/schemas/party'
    response_success_message:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: string
          format: string
          example: "action_successful"
    response_error:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: true
        code:
          type: integer
          format: integer
          example: 500
        errors:
          type: string
          format: string
          example: "any error"