openapi: 3.0.3
info:
  title: Party Organizer
  description: This is the server's swagger file for the Party Organizer project
  version: 1.2.1
servers:
  - url: http://localhost:8080/api/v1/
paths:
  /party:
    post:
      tags:
        - party
      summary: Create a party
      description: Create a party
      requestBody:
        description: Party object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/party_body_idless"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /party/{id}:
    get:
      tags:
        - party
      summary: Get a party
      description: Get a party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
    put:
      tags:
        - party
      summary: Update a party
      description: Update a party
      requestBody:
        description: Party object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/party_body_idless"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
    delete:
      tags:
        - party
      summary: Delete a party
      description: Delete a party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_message"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"

  /party/getPartiesByOrganizerId/:
    get:
      tags:
        - party
      summary: Get parties where the user is the organizer
      description: Get parties where the user is the organizer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /party/getPartiesByParticipantId/:
    get:
      tags:
        - party
      summary: Get parties where the user is a participant
      description: Get parties where the user is a participant
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /party/getPublicParties/:
    get:
      tags:
        - party
      summary: Get public parties
      description: Get public parties
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_party_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /party/getParticipants/{party_id}:
    get:
      tags:
        - party
      summary: Get participants of a party
      description: Get participants of a party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_user_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
components:
  schemas:
    party_body:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              format: integer
              example: 6
        - $ref: '#/components/schemas/party_body_idless'
    party_body_idless:
      type: object
      properties:
        place:
          type: string
          format: string
          example: "Budapest"
        name:
          type: string
          format: string
          example: "party name"
        google_maps_link:
          type: string
          format: string
          example: "https://maps.app.goo.gl/BRWibuuYXGPDiAWP9"
        facebook_link:
          type: string
          format: string
          example: "https://www.facebook.com/"
        whatsapp_link:
          type: string
          format: string
          example: "https://web.whatsapp.com/"
        is_private:
          type: boolean
          format: boolean
          example: true
        access_code_enabled:
          type: boolean
          format: boolean
          example: false
        access_code:
          type: string
          format: string
          example: "DD45H1A"
    user:
      type: object
      properties:
        id:
          type: integer
          format: integer
          example: 23
        username:
          type: string
          format: string
          example: "Joseph"
        email:
          type: string
          format: string
          example: "totally@real.email"
    response_success_party_data:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          $ref: '#/components/schemas/party_body'
    response_success_party_data_array:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/party_body'
    response_success_user_data_array:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/user'
    response_success_message:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: string
          format: string
          example: "action_successful"
    response_error:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: true
        code:
          type: integer
          format: integer
          example: 500
        errors:
          type: string
          format: string
          example: "any error"