openapi: 3.0.3
info:
  title: Party Organizer
  description: This is the server's swagger file for the Party Organizer project
  version: 1.2.1
servers:
  - url: http://localhost:8080/api/v1/
paths:
  /drinkRequirement:
    post:
      tags:
        - Drink Requirement
      summary: Create a drink requirement
      description: Create a drink requirement
      requestBody:
        description: Drink requirement object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/drink_requirement_body_idless"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_drink_requirement_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /drink_requirement/{id}:
    get:
      tags:
        - Drink Requirement
      summary: Get a drink requirement
      description: Get a drink requirement
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_drink_requirement_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
    put:
      tags:
        - Drink Requirement
      summary: Update a drink requirement
      description: Update a drink requirement
      requestBody:
        description: Drink requirement object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/drink_requirement_body_idless"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_drink_requirement_data"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
    delete:
      tags:
        - Drink Requirement
      summary: Delete a drink requirement
      description: Delete a drink requirement
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_message"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"

  /drink_requirement/getByPartyId/{party_id}:
    get:
      tags:
        - Drink Requirement
      summary: Get all drink requirements for a party
      description: Get all drink requirements for a party
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_drink_requirement_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
components:
  schemas:
    drink_requirement_body:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              format: integer
              example: 6
        - $ref: '#/components/schemas/drink_requirement_body_idless'
    drink_requirement_body_idless:
      type: object
      properties:
        party_id:
          type: integer
          format: integer
          example: 2
        type:
          type: string
          format: string
          example: "whisky"
        target_quantity:
          type: integer
          format: integer
          example: 2,6
        quantity_mark:
          type: string
          format: string
          example: "L"
    response_success_drink_requirement_data:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          $ref: '#/components/schemas/drink_requirement_body'
    response_success_drink_requirement_data_array:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/drink_requirement_body'
    response_success_message:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: string
          format: string
          example: "action_successful"
    response_error:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        errors:
          type: string
          format: string
          example: "any error"