openapi: 3.0.3
info:
  title: Party Organizer
  description: This is the server's swagger file for the Party Organizer project
  version: 1.2.1
servers:
  - url: http://localhost:8080/api/v1/
paths:
  /user/login/:
    post:
      tags:
        - User
      summary: User login
      description: User login
      requestBody:
        description: Login request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/login_request_body"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_jwt"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /user/register:
    post:
      tags:
        - User
      summary: User registration
      description: User registration
      requestBody:
        description: Register request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/register_request_body"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_message"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
  /user/getFriends/:
    get:
      tags:
        - User
      summary: Get all friend of a user
      description: Get all friend of a user
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_success_user_data_array"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "406":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_error"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          format: integer
          example: 23
        username:
          type: string
          format: string
          example: "Joseph"
        email:
          type: string
          format: string
          example: "totally@real.email"
    register_request_body:
      type: object
      properties:
        username:
          type: string
          format: string
          example: "Joseph"
        email:
          type: string
          format: string
          example: "totally@real.email"
        password:
          type: string
          format: string
          example: "secret"
        confirm_password:
          type: string
          format: string
          example: "secret"
    login_request_body:
      type: object
      properties:
        username:
          type: string
          format: string
          example: "Joseph"
        password:
          type: string
          format: string
          example: "secret"
    response_success_user_data_array:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/user'
    response_success_jwt:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: object
          properties:
            jwt:
              type: string
              format: string
              example: "ayhhbGciOiJIUzI1NiIsInR5cCI6IkpnVCJr.eyJlbWFmbCI6Im5vY2FwQG5vY2FwLm5vY2FwIiwiZXhwIjoxNzMxMTExMzY4LCJpYXQiOjE3MzEwMjQ5NjgsImlkIjoiNSIsImlzcyI6ImFzayBwZXRpIGFib3V0IHRoaXMiLCJuYmYiOjE3MzEwMjQ5NjgsInN1YiI6IjUiLCJ1c2VybmFtZSI6IjQ0NeJf.g7BzbRvLWqCI_R8eW95uJwaYHkGDN15h0EwMNaZcdKI"
    response_success_message:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: false
        code:
          type: integer
          format: integer
          example: 200
        data:
          type: string
          format: string
          example: "action_successful"
    response_error:
      type: object
      properties:
        is_error:
          type: boolean
          format: boolean
          example: true
        code:
          type: integer
          format: integer
          example: 500
        errors:
          type: string
          format: string
          example: "any error"