package configuration

const DEFAULT_LOCAL_DB_NAME = "application.db"

const JWT_SINGING_KEY_ENV_KEY = "JWT_SINGING_KEY"
const AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
const AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
const AWS_REGION_ENV_KEY = "AWS_REGION"
const AWS_BUCKET_NAME_ENV_KEY = "AWS_BUCKET_NAME"

var checkEnvKeyOnSetup = []string{JWT_SINGING_KEY_ENV_KEY, AWS_ACCESS_KEY_ID_ENV_KEY, AWS_SECRET_ACCESS_KEY_ENV_KEY, AWS_REGION_ENV_KEY, AWS_BUCKET_NAME_ENV_KEY}
